계좌 생성 API
kookmin-sw/capstone-2023-45 pull request #45
Opened 2023-03-28 13:19 UTC by jeonghi

* 유저 인증 연동
* 은행 계좌, 계좌 거래, 은행 지점 엔티티 정의
* 은행 계좌 컨트롤러 생성

2023-03-28 13:24 UTC, jeonghi commented
@okps123 @BbingDdang 불필요한 커밋 메시지들이 섞여버렸습니다...

2023-03-29 17:18 UTC, okps123 requested changes
기존에 합병된 커밋이 다시 추가된걸로 보이는데
작업하신 부분만 다시 정리해서 올려주세요~

2023-03-29 17:18 UTC, okps123 commented on backend/timebank/build.gradle.kts
> +
암호화하는데 시큐리티가 필요한가요?

2023-03-29 17:18 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/exception/ApplicationErrorCode.kt
> +    BANK_ERROR("BANK_ERROR", "뱅킹 서버 오류입니다.")
프론트엔드에서 구분해야할 오류가 아니면 일반 오류롤 사용하거나 더 상세하게 구분할 필요가 있을 것 같아요.

2023-03-31 05:37 UTC, closed without merging