은행 계좌 생성 API
kookmin-sw/capstone-2023-45 pull request #46
Opened 2023-03-31 07:17 UTC by jeonghi

* 은행 계좌, 은행 지점 엔티티 정의
* 은행 계좌 생성 컨트롤러, 서비스 정의

2023-03-31 08:33 UTC, okps123 requested changes

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/service/bank/BankAccountCreateService.kt
> +        if (isAccountNumberExists(accountNumber)) Exception(ConflictException(message = "Account number $accountNumber already exists"))
Exception을 return하는 이유가 있나요?
오류 메세지도 유저가 이해할 수 있는 내용으로 변경해주세요~

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/service/bank/BankAccountCreateService.kt
> +            Exception(ConflictException(message = "Account with ID $accountId already has bank account"))
위에 코멘트랑 동일한 의견입니다~

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/service/bank/BankAccountCreateService.kt
> +        val balance: Int,
돈은 연산을 고려해서 BigDecimal 자료형으로 변경하는게 좋을 것 같아요.
https://www.icatpark.com/entry/%EC%99%9C-%EB%8F%88-%EA%B3%84%EC%82%B0%EC%97%90%EB%8A%94-Floating-type%EC%9D%84-%EC%93%B0%EB%A9%B4-%EC%95%88%EB%90%98%EB%82%98

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/domain/model/BankAccount.kt
> +    var balance: Int,
위 코멘트랑 동일하게 BigDecimal로 다루는게 좋을 것 같아요.

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/domain/model/BankAccount.kt
> +    var updatedAt: LocalDateTime = LocalDateTime.now(),
BaseTimeEntity를 사용해주세요.

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/service/bank/BankAccountCreateService.kt
> +            .orElseThrow { NotFoundException(message = "Bank account with ID $bankAccountId not found") }
오류 메세지는 유저에게 안내할 수 있는 메세지로 적어주세요.

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/service/bank/BankAccountCreateService.kt
> +            password = encryptedPin,
PIN과 Password는 구분하는게 좋을 것 같아요.

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/domain/model/BankAccount.kt
> +    val ownerType: OwnerType? = null,
ownerType이 null이 될 수 있나요?
@Column 속성에 length도 설정해주세요.

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/service/bank/BankAccountCreateService.kt
> +    fun isAccountHasBankAccount(accountId: Long): Boolean {
함수 이름은 is~로 계좌를 가지고 있는지 검사하는 형태이지만
이미 가지고 있는 경우 thorw가 발생하고 있어서 함수 이름과 다른 행동을 하는 것 같아요.

validate- 내지는 check-와 같이 함수 이름을 변경하거나, throw하지 않고 이미 있는 경우 true를 반환하도록 변경하는게 어떨까요?

2023-03-31 08:33 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/service/bank/BankAccountCreateService.kt
> +        return getBankAccountById(accountId) != null
위에서 조회했는데 다시 조회하는 이유가 무엇인가요?

2023-03-31 08:36 UTC, okps123 requested changes

2023-03-31 08:36 UTC, okps123 commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/domain/repository/AccountJpaRepository.kt
> +    fun getAccountById(id: Long): Account?
get과 find는 구분하는게 좋은데요.
get의 경우 객체를 얻어오지 못하면 throw하는 형태로 많이 사용하고 있어서
findAccountById 내지는 Not Null을 반환하도록 하는게 좋을 것 같아요.

2023-03-31 08:47 UTC, jeonghi commented on backend/timebank/src/main/kotlin/kookmin/software/capstone2023/timebank/application/service/bank/BankAccountCreateService.kt
> +        if (isAccountNumberExists(accountNumber)) Exception(ConflictException(message = "Account number $accountNumber already exists"))
```kotlin
// 계좌번호 생성
private fun generateAccountNumber(account: Account, branch: BankBranch): String {
    val accountCode = account.id.toString().padStart(2, '0')
    val branchCode = branch.id.toString().padStart(2, '0')
    val randomCode = (10..99).random().toString()

    val accountNumber = "$accountCode$branchCode$randomCode"

    if (isAccountNumberExists(accountNumber)) {
        throw ConflictException("이미 사용 중인 계좌번호입니다.")
    }

    return accountNumber
}
```

@okps123 다음과 같이 수정하면 어떨까요?

2023-04-04 14:28 UTC, okps123 approved these changes

2023-04-06 02:19 UTC, BbingDdang approved these changes
확인했습니다~

2023-04-07 08:49 UTC, merged